version: '3.3'
services:
  rabbitmq-server:
    image: rabbitmq:3.8.1
    hostname: "rabbitmq-server"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq-server"

  hhapigateway:
    image: fernandopfh/hhapigateway:0.6dev
    depends_on:
      - rabbitmq-server
    tty: true
    ports:
      - "5000:5000"

  hhgetdb:
    image: fernandopfh/hhgetdb:0.7dev
    depends_on:
      - rabbitmq-server
    tty: true
    volumes:
      - "/home/fernando/Desktop/Documentos/Real/HelpingHand/DataBase:/DB"
    restart: always

  hhsetdb:
    image: fernandopfh/hhsetdb:0.3dev
    depends_on:
      - rabbitmq-server
    tty: true
    volumes:
      - "/home/fernando/Desktop/Documentos/Real/HelpingHand/DataBase:/DB"
    restart: always

volumes:
  hhgetdb:
  hhsetdb:
